const STORE='crna-nce-progress-v1',BANK='crna-nce-bank-v1';
const demo=[{id:'DEMO-001',domain:'Basic Sciences',stem:'A sample question is loaded so the app is usable before importing your CRNA NCE question bank.',choices:{A:'Select this to see how answer checking works.',B:'This is a distractor.',C:'This is another distractor.',D:'This is another distractor.'},answer:'A',rationale:'Replace this demo item by importing a generated CRNA NCE JSON question bank from the Library tab.'}];
let qs=load(BANK,demo), prog=load(STORE,{}), cur=null, picked=null, exam=null, timer=null;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(){localStorage.setItem(STORE,JSON.stringify(prog));stats();progress()}
function saveBank(){localStorage.setItem(BANK,JSON.stringify(qs))}
document.addEventListener('DOMContentLoaded',()=>{bind();domains();practice();review();progress();library();stats();loadGenerated()});
async function loadGenerated(){if(localStorage.getItem(BANK))return;try{let r=await fetch('data/questions.json',{cache:'no-store'});if(!r.ok)return;let d=await r.json(),a=Array.isArray(d)?d:d.questions;if(a?.length){qs=norm(a);saveBank();domains();practice();review();progress();library();stats()}}catch{}}
function bind(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');review();progress();library()});$('domain').onchange=practice;$('filter').onchange=practice;$('next').onclick=practice;$('check').onclick=check;$('flag').onclick=()=>{if(!cur)return;entry(cur.id).flagged=!entry(cur.id).flagged;save();practice(cur.id)};document.querySelectorAll('[data-conf]').forEach(b=>b.onclick=()=>{if(!cur)return;entry(cur.id).confidence=b.dataset.conf;save();conf()});$('reset').onclick=()=>{if(confirm('Reset all answer history and flags?')){prog={};save();practice();review()}};$('startExam').onclick=startExam;$('prevExam').onclick=()=>move(-1);$('nextExam').onclick=()=>move(1);$('finishExam').onclick=finish;$('reviewFilter').onchange=review;$('importFile').onchange=importJson;$('exportProgress').onclick=()=>download('crna-nce-progress.json',prog)}
function domains(){let d=['All domains',...new Set(qs.map(q=>q.domain||'Uncategorized'))].sort((a,b)=>a==='All domains'?-1:a.localeCompare(b));$('domain').innerHTML=d.map(x=>`<option>${esc(x)}</option>`).join('')}
function pool(){let d=$('domain').value,f=$('filter').value;return qs.filter(q=>{let e=prog[q.id]||{};return(d==='All domains'||(q.domain||'Uncategorized')===d)&&(f==='all'||f==='unanswered'&&!e.attempts||f==='missed'&&e.lastCorrect===false||f==='flagged'&&e.flagged)})}
function score(q){let e=prog[q.id]||{},s=1;if(!e.attempts)s+=8;if(e.lastCorrect===false)s+=6;if(e.flagged)s+=4;if(e.confidence==='low')s+=3;if(e.confidence==='high'&&e.lastCorrect)s-=3;return s}
function choose(a){if(!a.length)return null;let r=[...a].sort((a,b)=>score(b)-score(a));return r[Math.floor(Math.random()*Math.min(5,r.length))]}
function practice(id){cur=id?qs.find(q=>q.id===id):choose(pool());picked=null;$('feedback').className='feedback hidden';$('feedback').innerHTML='';if(!cur){$('qid').textContent='No question';$('qdomain').textContent='';$('stem').textContent='No questions match the current filters.';$('choices').innerHTML='';return}$('qid').textContent=cur.id;$('qdomain').textContent=cur.domain||'Uncategorized';$('stem').textContent=cur.stem;$('choices').innerHTML=choices(cur,'practice');conf()}
function choices(q,mode){return Object.entries(q.choices||{}).map(([k,t])=>`<button class="choice" data-mode="${mode}" data-answer="${esc(k)}"><b>${esc(k)}.</b> ${esc(t)}</button>`).join('')}
document.addEventListener('click',e=>{let c=e.target.closest('.choice');if(!c)return;if(c.dataset.mode==='practice'){picked=c.dataset.answer;document.querySelectorAll('#choices .choice').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')}if(c.dataset.mode==='exam'&&exam){exam.answers[exam.index]=c.dataset.answer;examQ()}});
function check(){if(!cur||!picked)return;let ok=picked===cur.answer,e=entry(cur.id);e.attempts=(e.attempts||0)+1;e.correct=(e.correct||0)+(ok?1:0);e.lastCorrect=ok;e.lastAnswer=picked;e.updatedAt=new Date().toISOString();save();document.querySelectorAll('#choices .choice').forEach(b=>{b.classList.toggle('correct',b.dataset.answer===cur.answer);b.classList.toggle('incorrect',b.dataset.answer===picked&&!ok)});$('feedback').className=`feedback ${ok?'good':'bad'}`;$('feedback').innerHTML=`<b>${ok?'Correct':'Correct answer: '+esc(cur.answer)}</b><p>${esc(cur.rationale||'No rationale provided.')}</p>`}
function entry(id){return prog[id]||(prog[id]={})}
function conf(){let e=prog[cur.id]||{};document.querySelectorAll('[data-conf]').forEach(b=>b.classList.toggle('active',b.dataset.conf===e.confidence));$('flag').textContent=e.flagged?'Unflag':'Flag'}
function startExam(){let n=Math.max(1,Math.min(Number($('examSize').value)||25,qs.length));exam={set:[...qs].sort(()=>Math.random()-.5).slice(0,n),answers:Array(n).fill(null),index:0,started:Date.now()};$('examResults').className='feedback hidden';clearInterval(timer);timer=setInterval(tick,1000);examQ()}
function examQ(){if(!exam)return;let q=exam.set[exam.index];$('examProgress').textContent=`Question ${exam.index+1} of ${exam.set.length}`;$('examStem').textContent=q.stem;$('examChoices').innerHTML=choices(q,'exam');document.querySelectorAll('#examChoices .choice').forEach(b=>b.classList.toggle('selected',b.dataset.answer===exam.answers[exam.index]));tick()}
function move(d){if(!exam)return;exam.index=Math.max(0,Math.min(exam.set.length-1,exam.index+d));examQ()}
function tick(){if(!exam)return;let s=Math.floor((Date.now()-exam.started)/1000);$('timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function finish(){if(!exam)return;clearInterval(timer);let c=0;exam.set.forEach((q,i)=>{let ok=exam.answers[i]===q.answer;if(ok)c++;let e=entry(q.id);e.attempts=(e.attempts||0)+1;e.correct=(e.correct||0)+(ok?1:0);e.lastCorrect=ok;e.lastAnswer=exam.answers[i];e.updatedAt=new Date().toISOString()});save();$('examResults').className='feedback';$('examResults').innerHTML=`<b>Score: ${c}/${exam.set.length} (${Math.round(c/exam.set.length*100)}%)</b><p>Missed items are now available in Review.</p>`}
function review(){let f=$('reviewFilter')?.value||'missed',rows=qs.filter(q=>{let e=prog[q.id]||{};return f==='missed'&&e.lastCorrect===false||f==='flagged'&&e.flagged||f==='all'&&e.attempts});$('reviewList').innerHTML=rows.map(q=>{let e=prog[q.id]||{};return`<article class="item"><h3>${esc(q.id)} · ${esc(q.domain||'Uncategorized')}</h3><p>${esc(q.stem)}</p><p><b>Your last answer:</b> ${esc(e.lastAnswer||'None')} · <b>Correct:</b> ${esc(q.answer)}</p><p>${esc(q.rationale||'No rationale provided.')}</p></article>`}).join('')||'<article class="item"><h3>No review items yet</h3><p>Missed and flagged questions will appear here.</p></article>'}
function progress(){let m=new Map();qs.forEach(q=>{let d=q.domain||'Uncategorized',e=prog[q.id]||{},x=m.get(d)||{total:0,att:0,c:0};x.total++;x.att+=e.attempts||0;x.c+=e.correct||0;m.set(d,x)});$('progressGrid').innerHTML=[...m].map(([d,x])=>{let p=x.att?Math.round(x.c/x.att*100):0;return`<article class="metric"><h3>${esc(d)}</h3><div class="bar"><div class="fill" style="width:${p}%"></div></div><p>${p}% correct across ${x.att} attempts · ${x.total} questions</p></article>`}).join('')}
function library(){let m=new Map();qs.forEach(q=>m.set(q.domain||'Uncategorized',(m.get(q.domain||'Uncategorized')||0)+1));$('domains').innerHTML=[...m].map(([d,c])=>`<div class="domain"><span>${esc(d)}</span><b>${c}</b></div>`).join('')}
async function importJson(e){let f=e.target.files[0];if(!f)return;let d=JSON.parse(await f.text()),a=Array.isArray(d)?d:d.questions;if(!Array.isArray(a)){alert('The selected file does not contain a questions array.');return}qs=norm(a);saveBank();domains();practice();review();progress();library();stats()}
function norm(a){return a.map((q,i)=>({id:String(q.id||`Q${String(i+1).padStart(3,'0')}`),domain:q.domain||q.category||'Uncategorized',stem:q.stem||q.question||'',choices:q.choices||{},answer:String(q.answer||q.correctAnswer||'').trim().toUpperCase(),rationale:q.rationale||q.explanation||''}))}
function stats(){$('bankCount').textContent=qs.length;$('masteredCount').textContent=qs.filter(q=>{let e=prog[q.id]||{};return e.lastCorrect&&e.confidence==='high'}).length}
function download(name,data){let b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
